language: ruby
cache: bundler

before_install:
  - gem install utopia # Install all dependencies.
  # For testing purposes:
  - git config --global user.email "samuel@oriontransfer.net"
  - git config --global user.name "Samuel Williams"

matrix:
  include:
    - rvm: 2.3
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.6
      env: COVERAGE=BriefSummary,Coveralls
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: truffleruby
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: truffleruby

env: BENCHMARK=true